/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author nataniel
 */
public class TelaLogin extends javax.swing.JFrame {

    private String user, senha;
    
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jSenha = new javax.swing.JPasswordField();
        jTextLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jlLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jToggleButton1.setText("ENTRAR");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(340, 150, 80, 32);
        getContentPane().add(jSenha);
        jSenha.setBounds(320, 102, 110, 30);
        getContentPane().add(jTextLogin);
        jTextLogin.setBounds(320, 70, 110, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-login.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 270, 200);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Acesso Restrito");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 30, 200, 30);

        jlSenha.setText("Senha: ");
        getContentPane().add(jlSenha);
        jlSenha.setBounds(270, 110, 60, 16);

        jlLogin.setText("Login: ");
        getContentPane().add(jlLogin);
        jlLogin.setBounds(270, 80, 37, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundoLogin.jpg"))); // NOI18N
        jLabel1.setText("Senha");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 200);

        setSize(new java.awt.Dimension(516, 237));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        user = "admin";
        senha = "13";
        String senhaString = new String(jSenha.getPassword());
        if((jTextLogin.getText().equals(user)) && (senhaString.equals(senha))) {
            telaMenu tm = new telaMenu();
            tm.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Acesso NEGADO!");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jSenha;
    private javax.swing.JTextField jTextLogin;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlSenha;
    // End of variables declaration//GEN-END:variables
}
